### ISSUE TITLE
dotnetcore 3.1 update 

### ISSUE THREAD

**Issue by kodlar** [MV10/WebSocketExample#1]
this codes working well on Dotnet core 2.2 Any update for 3.1

1- IWebHostEnvironment deprecated in startup.cs, what object do we use?
2- In program.cs  the main method  contains    Host.CreateDefaultBuilder(args).ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseUrls(new string[] { @"http://localhost:8080/" });
                    webBuilder.UseStartup<Startup>();
                })
                .Build()
                .Run();
When you update Microsoft.Extensions.Hosting the ConfigureWebHostDefaults method deprecated. Any idea how can we solve this?
Thanks

**Comment by MV10** [comment]
Hi Kodlar, the article and the code were written using ASP.NET Core 3.0, not 2.2. I'm not sure what you're seeing, but `ConfigureWebHostDefaults` was new in 3.0 and is not deprecated. With the ASP.NET Core 3.0 release they did deprecate the old `WebHostBuilder` because 3.x is built upon the Generic Host infrastructure.

Here is the [reference](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.generichostbuilderextensions.configurewebhostdefaults?view=aspnetcore-3.1) and the second example in [this](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1#set-up-a-host) document shows the use of `ConfigureWebHostDefaults`.

**Comment by kodlar** [comment]
Why I suppose dotnet.core 2.2 because of this :)  Look at the screenshot. Can you update the description text?
![image](https://user-images.githubusercontent.com/1201697/71978372-35283a00-322c-11ea-82ed-159d781c9c04.png)

By the way, I created my project infrastructure console app with Dotnet core 3.1. When I copy your code ConfigureWebHostDefaults not found.  I update Microsoft.AspNetCore.Hosting and
Microsoft.Extensions.Hosting. But it doesn't solve my problem. 

![image](https://user-images.githubusercontent.com/1201697/71979213-2fcbef00-322e-11ea-8727-13ea1c682d1f.png)

As you can see IHostBuilder does not contain a definition for ConfigureWebHostDefaults 
I get this error message
Error	CS1061	'IHostBuilder' does not contain a definition for 'ConfigureWebHostDefaults' and no accessible extension method 'ConfigureWebHostDefaults' accepting a first argument of type 'IHostBuilder' could be found (are you missing a using directive or an assembly reference?)	

Which assembly should I add?

**Comment by MV10** [comment]
> Why I suppose dotnet.core 2.2 because of this :) Look at the screenshot. Can you update the description text?

😄 Thanks, I created the repository a few days before 3.0 was released! Fixed now.

For a server under .NET Core 3.0 or later, you should start with a blank ASP.NET Core project, not a console program. 

At the start of my [article](https://mcguirev10.com/2019/08/18/minimal-full-feature-kestrel-websocket-server.html) about the Kestrel version, I mentioned my original goal was to write a bare-bones example. I had planned to start from a console program, too, but Kestrel and ASP.NET Core have so many dependencies, it doesn't make sense to waste time trying to figure out which ones you need. Using the ASP.NET Core SDK won't add any unneeded dependencies to your final build, the latest compilers do a pretty good job of only including what is actually in use.

**Comment by kodlar** [comment]
Thanks jon
